services:
  rabbitmq-main:
    image: "rabbitmq:4.1-management-alpine"
    ports:
      - "5672"
      - "15672"
    volumes:
      - /var/lib/rabbitmq:/var/lib/rabbitmq
      - /var/log/rabbitmq:/var/log/rabbitmq
    restart: "on-failure"