[project]
name = "celery-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "celery>=5.5.3",
    "fastapi[standard]>=0.115.12",
    "flower>=2.0.1",
    "mypy>=1.16.0",
    "ruff>=0.11.13",
]
